apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: checkers
build:
  platforms:
    - linux/amd64
  local:
    push: true
  artifacts:
    - image: checkers
      context: .
deploy:
  kubeContext: admin@ee-lte-1.codemowers.io
  helm:
    releases:
      - name: checkers
        chartPath: chart
        namespace: demo
        setValues:
          env.AUTH_MODE: optional
        setValueTemplates:
          image: "{{.IMAGE_FULLY_QUALIFIED_checkers}}"
