apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    skaffold.dev/keep: "true"
  name: checkers-redis
spec:
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.37.0
  authentication:
    passwordFromSecret:
      name: checkers-redis-auth
      key: password
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
