apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: checkers
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: checkers-web
                port:
                  name: http
  tls:
    - secretName: checkers-tls
