{{- $services := list "checkers-redis" }}
{{- if .Values.https.enabled }}
{{- $services = prepend $services "checkers-web" }}
{{- end }}
{{- range $service := $services }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $service }}
spec:
  dnsNames:
    - {{ $service }}
  issuerRef:
    name: cluster-tls-issuer
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
