apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: checkers-nextauth
spec:
  forceRegenerate: false
  fields:
    - fieldName: secret
      encoding: hex
      length: "32"
