apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  labels:
    skaffold.dev/keep: "true"
  name: checkers-redis-auth
spec:
  forceRegenerate: false
  fields:
    - fieldName: password
      encoding: hex
      length: "32"
