{{- if .Values.https.enabled }}
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: checkers-tls
spec:
  serverName: checkers-web.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
