apiVersion: v1
kind: Service
metadata:
  name: checkers-web
  labels:
    app: checkers-web
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: {{ printf "%s-checkers@kubernetescrd" .Release.Namespace | quote }}
spec:
  selector:
    app: checkers-web
  ports:
    - name: http
      port: 3000
      targetPort: http
